apiVersion: v1
kind: Secret

metadata:
  name: wisora-secret

type: Opaque

stringData:
  PORT: "3000"
  MONGO_URI: "mongodb+srv://prysh310704_db_user:9sJJQQ37FAy7nbxt@cluster0.ryie9q2.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "supersecretkey"
  CLIENT_URL: "https://wisora-frontend.onrender.com"
  CLOUDINARY_CLOUD_NAME: "dktypdlzl"
  CLOUDINARY_API_KEY: "545499399811956"
  CLOUDINARY_API_SECRET: "zpN7X18Zt3uuVCYK8khRt1mmZ9A"